name: duck
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/mishakuschenko/duck

environment:
  sdk: ^3.7.0

dependencies:
  http: ^1.3.0
  sqlite3: ^2.7.4

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
